### ISSUE TITLE
toast的居中方式是否不太好

### ISSUE THREAD

**Issue by ygtzz** [noru/vue-easy-toast#1]
```css
.et-wrapper {
    padding: 10px;
    left: 0;
    right: 0;
    margin: auto;
    width: auto;
    display: inline-block;
    max-width: 350px;
    min-width: 200px;
  }
```
当文字很少的时候，200px太宽了，用自适应的是否更好些，例如
```css
.et-wrapper {
    padding: 10px 30px;
    left: 50%;
    transform: translateX(-50%);
    display: inline-block;
    max-width: 300px;
  }
```
随文字增多而变宽
