### ISSUE TITLE
能开个接口 或者配置 加个全屏遮罩么？

### ISSUE THREAD

**Issue by ChowYoung** [noru/vue-easy-toast#16]
能开个接口 或者配置 加个全屏遮罩么？

**Comment by noru** [comment]
可以用css达到类似的效果：

```css
.et-wrapper::before {
    content: "";
    display: block;
    position: absolute;
    width: 861112px;
    height: 861112px;
    top: 0;
    left: 0;
    background-color: rgba(0,0,0,.4);
    z-index: -1;
}
```

但如果如果需要这样的效果，那么你要用的控件是Modal而不是Toast
